### ISSUE TITLE
pcb gerber file

### ISSUE THREAD

**Issue by Yeppers1** [retrobuiltRyan/Mini-Macro-Keyboard-v2#1]
i am extremely interested in builiding this project as i came across it on youtube.  your pcb on your marketplace is sold out.  i was wondering if you could provide the gerber files so that i may source a pcb myself?  if so, any recommendations on the pcb fabrication?

**Comment by retrobuiltRyan** [comment]
Hi, this will be back in stock in ~2wks.

**Comment by airbase9018** [comment]
second the motion here.

**Comment by retrobuiltRyan** [comment]
the larger 13key  variant (11key + 2 encoder) macro has the gerbers released to public
